### ISSUE TITLE
Task: Divise a way serve problems to users && how they will answer said questions

### ISSUE THREAD

**Issue by abelSemahegn** [Allen-ISD-Computer-Science/REPO_CybSecInvitational_2024#11]
- How will we give them questions
- How will they get instructions

Propose solutions to these problems
Summary Story: #10

**Comment by KrabbiePatty** [comment]
Create a Moodle course that all the teams will enroll in. Questions will be served as assignments.

**Comment by abelSemahegn** [comment]
This is a great sounds good!
