### ISSUE TITLE
Task: Make a new timeline for the whole event

### ISSUE THREAD

**Issue by abelSemahegn** [Allen-ISD-Computer-Science/REPO_CybSecInvitational_2024#20]
We need a new timeline for how the contest will look like.
Supports Story:  #19

**Comment by JamesMDungan** [comment]
2 alternative updated timelines

[https://app.diagrams.net/#G11V29mlNylhfqkrF9EplKzkpLT0C0KEpY](url)

**Comment by abelSemahegn** [comment]
Looks really good!! 👍
