### ISSUE TITLE
Task: list of schools

### ISSUE THREAD

**Issue by Richard-Jang** [Allen-ISD-Computer-Science/REPO_CybSecInvitational_2024#21]
Create a list of schools to invite to the event:

- email the administration and computer science team of that school
- figure out logistics of going in person to speak
- video and flyer advertisement

Support story: [#19](https://github.com/orgs/Allen-ISD-Computer-Science/projects/19/views/1?pane=issue&itemId=47695908)

**Comment by JamesMDungan** [comment]
List of districts
==========================
-Allen ISD
	-Allen High School
	-Allen STEAM Center
	-Lowery Freshman Center
-Plano ISD
	-Plano East
	-Plano West Senior High
	-Plano ISD Academy
	-Plano Senior High
	-Plano Jjaep
	-Hospital/Homebound
-Lovejoy ISD
	-Lovejoy High School
-Mckinney ISD
	-McKinney North High School
	-McKinney Boyd High School
	-McKinney High School
	-County Residential Center
	-Serenity High School
-Frisco ISD
	-Reedy High School
	-Wakeland High School
	-Liberty High School
	-Centennial High School
	-Independence High School
	-Lebanon Trail High School
	-Heritage High School
	-Frisco High School
	-Memorial High School
	-Lone Star High School
-Prosper ISD
	-Prosper High School
	-Rock Hill High School
-Richardson ISD
	-Richardson High School
	-Pearce High School
	-Lake Highlands High School
	-Berkner High School
-Murphy ISD
	-C A McMillen High School
-Wylie ISD
	-Wylie High School
	-Wylie East High School
	-Acheive Academy

**Comment by abelSemahegn** [comment]
James did it
