### ISSUE TITLE
Task: Plan the Registration process

### ISSUE THREAD

**Issue by JamesMDungan** [Allen-ISD-Computer-Science/REPO_CybSecInvitational_2024#8]
We need to determine how competitors will be registered, They need to be given a team number and get logged into the system. We need to create a way for Competitors to pre-register so the registration line isn't backlogged

Support Story: #4

**Comment by FarazPir** [comment]
Possible tool for registration:
[](https://github.com/acmutd/hackportal)

**Comment by FarazPir** [comment]
We've decided to handle registration by providing individuals who register with a QR code, and then they will use that QR code to check in when they arrive.

**Comment by FarazPir** [comment]
Idea: Create an ID number for each contestant, QR code will contain ID number
https://www.youtube.com/watch?v=fjkO0kHbbKw
https://www.youtube.com/watch?v=ZmQn5Jlj6jQ

**Comment by FarazPir** [comment]
Plan is to have a login system using MangoDB, after making an account users will get a QR Code that lets them sign in at the event.
